# Generated by Django 4.2.9 on 2025-03-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_add_moderation_fields_to_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentModerationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('post_image', 'Post Image'), ('post_video', 'Post Video'), ('message_image', 'Message Image'), ('message_video', 'Message Video'), ('avatar', 'Profile Avatar')], max_length=20)),
                ('content_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('error', 'Error Processing')], default='pending', max_length=10)),
                ('moderation_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('moderation_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='blockedpost',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
