# Generated by Django 4.2.9 on 2025-03-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_contentmoderationstatus_blockedpost_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image_moderation_passed',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_image_moderated',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_video_moderated',
        ),
        migrations.RemoveField(
            model_name='message',
            name='video_moderation_passed',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_moderated',
        ),
        migrations.RemoveField(
            model_name='post',
            name='moderation_passed',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='is_moderated',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='moderation_passed',
        ),
        migrations.RemoveField(
            model_name='postvideo',
            name='is_moderated',
        ),
        migrations.RemoveField(
            model_name='postvideo',
            name='moderation_passed',
        ),
    ]
