# Generated by Django 4.2.9 on 2025-03-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_update_moderation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='image_moderation_passed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_image_moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_video_moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='video_moderation_passed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='moderation_passed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='postimage',
            name='is_moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postimage',
            name='moderation_passed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='postvideo',
            name='is_moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postvideo',
            name='moderation_passed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contentmoderationstatus',
            name='content_type',
            field=models.CharField(choices=[('post_image', 'Post Image'), ('post_video', 'Post Video'), ('message_image', 'Message Image'), ('message_video', 'Message Video'), ('avatar', 'Profile Avatar'), ('comment', 'Comment')], max_length=20),
        ),
    ]
